[project]
org-name = "ballerina"
version = "@toml.version@"

[dependencies]
"ballerina/auth" = "@stdlib.auth.version@"
"ballerina/cache" = "@stdlib.cache.version@"
"ballerina/http" = "@stdlib.http.version@"
"ballerina/stringutils" = "@stdlib.stringutils.version@"
"ballerina/log" = "@stdlib.log.version@"
"ballerina/crypto" = "@stdlib.crypto.version@"
"ballerina/encoding" = "@stdlib.encoding.version@"
"ballerina/io" = "@stdlib.io.version@"
"ballerina/time" = "@stdlib.time.version@"
"ballerina/system" = "@stdlib.system.version@"
"ballerina/config" = "@stdlib.config.version@"
"ballerina/task" = "@stdlib.task.version@"
"ballerina/reflect" = "@stdlib.reflect.version@"
"ballerina/file" = "@stdlib.file.version@"
"ballerina/mime" = "@stdlib.mime.version@"
"ballerina/runtime" = "@stdlib.runtime.version@"
