[package]
org = "ballerina"
name = "jwt"
version = "2.9.0"
authors = ["Ballerina"]
keywords = ["security", "authentication", "jwt", "jwk", "jws"]
repository = "https://github.com/ballerina-platform/module-ballerina-jwt"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "jwt-native"
version = "2.9.0"
path = "../native/build/libs/jwt-native-2.9.0.jar"
