name: PR build

on: pull_request

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build
      - name: Generate CodeCov Report Try 1
        if: github.event_name == 'pull_request'
        id: uploadReport1
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          fail_ci_if_error: true
      - name: Wait after upload failure
        if: steps.uploadReport1.outcome == 'failure'
        run: |
          sleep 300s
      - name: Generate CodeCov Report Try 2
        if: steps.uploadReport1.outcome == 'failure'
        id: uploadReport2
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          fail_ci_if_error: true
      - name: Wait after upload failure
        if: steps.uploadReport2.outcome == 'failure'
        run: |
          sleep 300s
      - name: Generate CodeCov Report Try 3
        if: steps.uploadReport2.outcome == 'failure'
        id: uploadReport3
        uses: codecov/codecov-action@v2
        continue-on-error: true
        with:
          fail_ci_if_error: true
      - name: Wait after upload failure
        if: steps.uploadReport3.outcome == 'failure'
        run: |
          sleep 300s
      - name: Generate CodeCov Report Try 4
        if: steps.uploadReport3.outcome == 'failure'
        uses: codecov/codecov-action@v2

  windows-build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat build -Pdisable=jwks
